apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pv-claim
  labels:
    app: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  selector:
    matchLabels:
      app: ollama
  replicas: 1
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - ollama serve & sleep 10 && ollama pull llama2 && wait
          ports:
            - containerPort: 11434
          volumeMounts:
            - name: ollama-persistent-storage
              mountPath: /root/.ollama
      volumes:
        - name: ollama-persistent-storage
          persistentVolumeClaim:
            claimName: ollama-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
      nodePort: 31434
  type: NodePort
