#spring.h2.console.enabled=true
#spring.datasource.platform=h2
#spring.datasource.url=jdbc:h2:mem:testbd

spring.datasource.url=jdbc:mariadb://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:miola}?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:root}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=${SERVER_PORT:8082}
spring.data.rest.base-path=/api
spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
spring.ai.ollama.chat.options.model=${OLLAMA_CHAT_MODEL:llama2}
spring.ai.ollama.chat.options.temperature=${OLLAMA_TEMPERATURE:0.4}

# Spring Security default user
spring.security.user.name=admin
spring.security.user.password=admin
